name: mobile_app
description: "Mpepo Kitchen POS Mobile Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # Fixed Dart SDK constraint
  flutter: ">=3.16.0"     # Added Flutter SDK constraint

dependencies:
  flutter:
    sdk: flutter
  
  http: ^1.1.0
  provider: ^6.1.1
  # Add these for local storage:
  sqflite: ^2.3.0
  path: ^1.8.3
  printing: ^5.10.0
  pdf: ^3.10.4
  intl: ^0.20.2
  go_router: ^13.0.0
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.1  # Add this for network detection
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Add assets for logo and icon
  assets:
    - assets/images/logo.png
    - assets/icon/icon.png

# Launcher icon configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
